import admin from "../lib/firebaseAdmin";

import { FieldValue, type Timestamp } from "firebase-admin/firestore";
import MeetingDAO from "./MeetingDAO";

const db = admin.firestore();

export interface Chat {
  meetId?: string | null;
  ai_summary?: string | null;
  messages?: ChatMessage[] | null;
  createdAt?: Timestamp | null;
}

export type ChatMessage = {
  name: string;
  message: string;
  timestamp?: string;
};

export type ChatCreate = Omit<Chat, "messages" | "createdAt">;

/**
 * DAO for managing chat documents in Firestore.
 * Provides methods to create chats, save messages, add summaries,
 * and retrieve chats by ID or user.
 */
class ChatDAO {
  private collectionRef = db.collection("chat");

  /**
   * Creates a new chat document in Firestore using the meeting ID as the document ID.
   *
   * @param {ChatCreate} chatData - The initial data required to create the chat, including the meeting ID.
   *
   * @returns {Promise<{ success: true, id: string } | { success: false, error: string }>}
   *   - success: true and the created document ID if the chat is created successfully.
   *   - success: false and an error message if the operation fails.
   *
   * @description
   * This method initializes a chat document with empty messages and a server timestamp.
   * The chat is stored using the `meetId` as the document reference ID.
   */

  async createChat(
    chatData: ChatCreate,
  ): Promise<
    { success: true; id: string } | { success: false; error: string }
  > {
    try {
      const docRef = await this.collectionRef.doc(chatData.meetId as string);

      await docRef.set({
        ...chatData,
        messages: [],
        createdAt: admin.firestore.FieldValue.serverTimestamp(),
      });

      return { success: true, id: docRef.id };
    } catch (err: any) {
      console.error("Error añadiendo documento", err);
      return { success: false, error: err?.message ?? "Error desconocido" };
    }
  }

  /**
   * Saves a new message into an existing chat document identified by the meeting ID.
   *
   * @param {string} meetId - The ID of the meeting, used as the chat document identifier.
   * @param {ChatMessage} message - The message object to be appended to the chat.
   *
   * @returns {Promise<
   *   | { success: true; data: Chat }
   *   | { success: false; data: null; error?: string }
   * >}
   *   - success: true and the updated chat data if the message is saved successfully.
   *   - success: false and an error message if the update operation fails.
   *
   * @description
   * This method appends a message to the `messages` array of the chat document using `arrayUnion`.
   * After updating, it retrieves and returns the updated chat data.
   */
  async saveMessage(
    meetId: string,
    message: ChatMessage,
  ): Promise<
    | { success: true; data: Chat }
    | { success: false; data: null; error?: string }
  > {
    try {
      await this.collectionRef.doc(meetId).update({
        messages: FieldValue.arrayUnion(message),
      });

      const updatedChat = await this.collectionRef.doc(meetId).get();

      return {
        success: true,
        data: updatedChat.data() as Chat,
      };
    } catch (err: any) {
      console.error("Error agregando mensaje:", err);
      return {
        success: false,
        data: null,
        error: err?.message ?? "Error desconocido",
      };
    }
  }

  /**
   * Retrieves a chat document by its meeting ID.
   *
   * @param {string} meetId - The unique identifier of the meeting, used as the chat document ID.
   *
   * @returns {Promise<
   *   | { success: true; data: Chat }
   *   | { success: false; data: null; error?: string }
   * >}
   *   - success: true and the chat data if the document exists.
   *   - success: false and `data: null` if the chat is not found or an error occurs.
   *
   * @description
   * This method fetches the chat document from Firestore using the provided meeting ID.
   * If the document does not exist, it returns a failure response without throwing an error.
   * Errors during retrieval are logged and included in the response.
   */
  async getChatById(
    meetId: string,
  ): Promise<
    | { success: true; data: Chat }
    | { success: false; data: null; error?: string }
  > {
    try {
      const chatRef = await this.collectionRef.doc(meetId).get();

      if (!chatRef.exists) {
        return { success: false, data: null };
      }

      return { success: true, data: chatRef.data() as Chat };
    } catch (err: any) {
      console.error("Error consiguiendo el documento:", err);
      return {
        success: false,
        data: null,
        error: err?.message ?? "Error desconocido",
      };
    }
  }

  /**
   * Adds or updates the AI-generated summary for a specific chat.
   *
   * @param {string} meetId - The ID of the meeting, used as the identifier of the chat document.
   * @param {string} ai_summary - The summary text generated by the AI to be stored in the chat.
   *
   * @returns {Promise<
   *   | { success: true; data: Chat }
   *   | { success: false; data: null; error?: string }
   * >}
   *   - success: true and the updated chat data if the summary is successfully saved.
   *   - success: false and an error message if the update operation fails.
   *
   * @description
   * This method updates the `ai_summary` field of a chat document in Firestore.
   * After updating, it retrieves the updated chat data and returns it.
   * Any errors encountered during the process are logged and returned.
   */
  async addSummary(
    meetId: string,
    ai_summary: string,
  ): Promise<
    | { success: true; data: Chat }
    | { success: false; data: null; error?: string }
  > {
    try {
      await this.collectionRef.doc(meetId).update({
        ai_summary: ai_summary,
      });

      const updatedChat = await this.collectionRef.doc(meetId).get();

      return {
        success: true,
        data: updatedChat.data() as Chat,
      };
    } catch (err: any) {
      console.error("Error agregando resumen:", err);
      return {
        success: false,
        data: null,
        error: err?.message ?? "Error desconocido",
      };
    }
  }

  /**
   * Retrieves all chats associated with a specific user.
   *
   * @param {string} userId - The ID of the user whose chats should be fetched.
   *
   * @returns {Promise<
   *   | { success: true; data: Chat[] }
   *   | { success: false; data: null; error?: string }
   * >}
   *   - success: true and an array of chats belonging to the user.
   *   - success: false if meetings or chats cannot be retrieved, or if an error occurs.
   *
   * @description
   * This method performs a two-step relationship lookup:
   *   1. It retrieves all meetings created or attended by the given user.
   *   2. It retrieves all chats in the system.
   *
   * It then cross-matches meetings with chats by comparing the meeting ID with the `meetId`
   * field of each chat, returning only the chats that belong to the user's meetings.
   *
   * If either the meeting list or chat list fails to load, the method returns a failure response.
   * Errors are logged and included in the return value.
   */
  async getChatsByUser(
    userId: string,
  ): Promise<
    | { success: true; data: Chat[] }
    | { success: false; data: null; error?: string }
  > {
    try {
      const meetings = await MeetingDAO.getMeetingsByUser(userId);
      if (!meetings.success) {
        return { success: false, data: null };
      }

      const chats = await this.getAllChats();
      if (!chats.success) {
        return { success: false, data: null };
      }

      var userChats: Chat[] = [];

      for (var meeting of meetings.data) {
        for (var chat of chats.data) {
          if (meeting.id == chat.meetId) {
            userChats.push(chat);
          }
        }
      }

      return { success: true, data: userChats as Chat[] };
    } catch (err: any) {
      console.error("Error consiguiendo el documento:", err);
      return {
        success: false,
        data: null,
        error: err?.message ?? "Error desconocido",
      };
    }
  }

  /**
   * Retrieves all chat documents stored in the collection.
   *
   * @returns {Promise<
   *   | { success: true; data: Chat[] }
   *   | { success: false; data: null; error?: string }
   * >}
   *   - success: true with an array of all chat records if retrieval succeeds.
   *   - success: false if the query fails or an error occurs.
   *
   * @description
   * This method fetches the entire chat collection from Firestore.
   * It maps each document to its corresponding `Chat` object and returns the resulting list.
   *
   * If the retrieval fails or an exception is thrown, the error is logged and a failure
   * response is returned.
   */
  async getAllChats(): Promise<
    | { success: true; data: Chat[] }
    | { success: false; data: null; error?: string }
  > {
    try {
      const chatRef = await this.collectionRef.get();

      if (!chatRef) {
        return { success: false, data: null };
      }

      return {
        success: true,
        data: chatRef.docs.map((doc) => ({
          ...doc.data(),
        })) as Chat[],
      };
    } catch (err: any) {
      console.error("Error consiguiendo el documento:", err);
      return {
        success: false,
        data: null,
        error: err?.message ?? "Error desconocido",
      };
    }
  }
}

export default new ChatDAO();
