import admin from "../lib/firebaseAdmin";

import type { Timestamp } from "firebase/firestore";

const db = admin.firestore();

export interface User {
  name?: string | null;
  email?: string | null;
  age?: number | null;
  photoURL?: string | null;
  createdAt?: Timestamp | null;
  updatedAt?: Timestamp | null;
}

export type UserCreate = Omit<User, "id" | "createdAt" | "updatedAt">;
export type UserUpdate = Partial<Omit<User, "id" | "createdAt">>;

/**
 * Data Access Object (DAO) for managing User documents in Firestore.
 * Provides methods to create, retrieve, and update user records.
 */
class UserDAO {
  private collectionRef = db.collection("users");

  /**
   * Retrieves a user document from Firestore by its ID.
   *
   * The method reads the document from the "users" collection using the
   * provided `id`. If the document exists, it returns the user data cast
   * as `User`. If it does not exist, it returns `success: false` with
   * `data: null`.
   *
   * Any Firestore or runtime error is caught and returned with an
   * `error` message.
   *
   * @param id - The Firestore user document ID.
   * @returns An object indicating success or failure:
   *  - { success: true, data: User }
   *  - { success: false, data: null }
   *  - { success: false, data: null, error: string }
   */

  async getUserById(
    id: string,
  ): Promise<
    | { success: true; data: User }
    | { success: false; data: null; error?: string }
  > {
    try {
      const snap = await this.collectionRef.doc(id).get();
      if (!snap.exists) {
        return { success: false, data: null };
      }
      return { success: true, data: snap.data() as User };
    } catch (err: any) {
      console.error("Error consiguiendo documento:", err);
      return { success: false, data: null, error: err?.message };
    }
  }

  /**
   * Fetches a user by email using a Firestore query.
   *
   * Looks up the first document where `email` matches the provided value.
   * Returns the document ID and user data if found; otherwise returns
   * `success: false`. Errors are caught and returned with an error message.
   *
   * @param email - User email to search for.
   * @returns Success with `{ id, data }`, or failure with `id: null, data: null`.
   */
  async getUserByEmail(
    email: string,
  ): Promise<
    | { success: true; id: string; data: User }
    | { success: false; id: null; data: null; error?: string }
  > {
    try {
      const snap = await this.collectionRef
        .where("email", "==", email)
        .limit(1)
        .get();

      if (snap.empty) {
        return { success: false, id: null, data: null };
      }

      const doc = snap.docs[0];
      return { success: true, id: doc.id, data: doc.data() as User };
    } catch (err: any) {
      console.error("Error consiguiendo usuario:", err);
      return { success: false, id: null, data: null, error: err?.message };
    }
  }

  /**
   * Retrieves all users from the Firestore `users` collection.
   *
   * Returns an array of user documents (each including its Firestore ID).
   * If no documents exist, returns an empty array. Any errors during retrieval
   * are caught and returned with an error message.
   *
   * @returns Success with `{ users }`, or failure with an `error` message.
   */
  async getAllUsers(): Promise<
    { success: true; users: any[] } | { success: false; error: string }
  > {
    try {
      const snap = await this.collectionRef.get();

      if (snap.empty) {
        return { success: true, users: [] };
      }
      const users = snap.docs.map((doc) => ({
        id: doc.id,
        ...doc.data(),
      }));

      return { success: true, users };
    } catch (err: any) {
      console.error("Error consiguiendo usuarios:", err);
      return { success: false, error: err?.message || "Error desconocido" };
    }
  }

  /**
   * Creates a new user document in the `users` collection.
   *
   * Adds the provided user data along with `createdAt` and `updatedAt`
   * timestamps generated by Firestore. Returns the new document ID on success.
   *
   * @param userData - Fields required to create a new user.
   * @returns Success with `{ id }`, or failure with an `error` message.
   */
  async createUser(
    userData: UserCreate,
  ): Promise<
    { success: true; id: string } | { success: false; error: string }
  > {
    try {
      const docRef = await this.collectionRef.add({
        ...userData,
        createdAt: admin.firestore.FieldValue.serverTimestamp(),
        updatedAt: admin.firestore.FieldValue.serverTimestamp(),
      } as User);
      return { success: true, id: docRef.id };
    } catch (err: any) {
      console.error("Error añadiendo documento:", err);
      return { success: false, error: err?.message ?? "Error desconocido" };
    }
  }

  /**
   * Updates an existing user document with the provided data.
   *
   * Merges the given fields into the user record and refreshes the `updatedAt`
   * timestamp. Returns a success flag or an error message if the update fails.
   *
   * @param id - The ID of the user to update.
   * @param userData - Partial user fields to modify.
   * @returns `{ success: true }` on success, or `{ success: false, error }` on failure.
   */
  async updateUser(
    id: string,
    userData: UserUpdate,
  ): Promise<{ success: true } | { success: false; error: string }> {
    try {
      await this.collectionRef.doc(id).update({
        ...userData,
        updatedAt: admin.firestore.FieldValue.serverTimestamp(),
      } as Partial<User>);
      return { success: true };
    } catch (err: any) {
      console.error("Error actualizando documento:", err);
      return { success: false, error: err?.message ?? "Error desconocido" };
    }
  }

  /**
   * Deletes a user document by ID.
   *
   * Removes the specified user from the database. Returns a success flag or
   * an error message if the deletion fails.
   *
   * @param id - The ID of the user to delete.
   * @returns `{ success: true }` on success, or `{ success: false, error }` on failure.
   */
  async deleteUser(
    id: string,
  ): Promise<{ success: true } | { success: false; error: string }> {
    try {
      await this.collectionRef.doc(id).delete();
      return { success: true };
    } catch (err: any) {
      console.error("Error eliminando documento:", err);
      return { success: false, error: err?.message ?? "Error desconocido" };
    }
  }
}

export default new UserDAO();
